export const styles = {
  root: {
    backgroundImage: "url(/images/stadion.jpg)",
    backgroundSize: "100%",
    backgroundPosition: "center",
    height: "530px",
    display: "flex",
    justifyContent: "end",
    alignItems: "center",
    padding: "0 90px 0 0",
  },
  title: {
    width: "800px",
    textAlign: "right",
    fontFamily: "Montserrat Alternates",
    fontSize: "47px",
    color: "#FFFFFF",
    fontWeight: "300",
    lineHeight: "60px",
  },
  targetBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "50px",
  },
  targetTitle: {
    width: "800px",
    textAlign: "left",
    fontFamily: "Montserrat Alternates",
    fontSize: "37px",
    color: "#A25F4B",
    fontWeight: "300",
    lineHeight: "50px",
  },
  img: {
    width: "600px",
    height: "400px",
    borderRadius: "24px",
  },
  stadiumBox: {
    backgroundImage: "url(/images/fans-on-stadium.jpg)",
    backgroundSize: "100%",
    backgroundPosition: "center",
    height: "530px",
    display: "flex",
    justifyContent: "end",
    alignItems: "center",
    padding: "0 90px 0 0",
    marginTop: "50px",
  },
  stadiumTitle: {
    width: "800px",
    textAlign: "right",
    fontFamily: "Montserrat Alternates",
    fontSize: "47px",
    color: "#FFFFFF",
    fontWeight: "300",
    lineHeight: "60px",
  },
  pubBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "50px",
  },
  pubTitle: {
    width: "500px",
    textAlign: "left",
    fontFamily: "Montserrat Alternates",
    fontSize: "37px",
    color: "#229542",
    fontWeight: "300",
    lineHeight: "50px",
  },
  mapBox: {
    backgroundImage: "url(/images/pitch.jpg)",
    backgroundSize: "100%",
    backgroundPosition: "center",
    height: "530px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "50px",
  },
  mapTitle: {
    width: "500px",
    textAlign: "center",
    fontFamily: "Montserrat Alternates",
    fontSize: "37px",
    color: "#FFFFFF",
    fontWeight: "300",
    lineHeight: "50px",
  },
  mapButton: {
    color: "#FFFFFF",
    marginTop: "20px",
    width: "280px",
    border: "2px solid #00000000",
    borderRadius: "15px",
    ":hover": { border: "2px solid #FFFFFF" },
  },
};
